### ISSUE TITLE
Cannot contribute the Nov. 11 update using the instructions

### ISSUE THREAD

**Issue by FakeSalamander** [Yareeeef/MapleLegends-installer#1]
The Wineskin links for the newest mandatory update  are not from Google Drive, but rather from Mega.nz and sync.com respectively. 

Is it possible to edit the install script to support one of those instead?

**Comment by Yareeeef** [comment]
Any place that supports direct downloads should be easy to add, sure.

Ill take a look at it soon :)

**Comment by Yareeeef** [comment]
Hey, I added support for mega.nz links, also updated the direct url with the latest version. if you update it should just work (tm).

I don't know how to get sync.com working tho. Similarly to mega.nz they do some clever encryption but thats a bit over my head and couldn't find a reference for it.
